/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type XMin = number;
export type XMax = number;
export type YMin = number;
export type YMax = number;
export type ZMin = number;
export type ZMax = number;

export interface GeoModelExtent {
  x_min: XMin;
  x_max: XMax;
  y_min: YMin;
  y_max: YMax;
  z_min: ZMin;
  z_max: ZMax;
  [k: string]: unknown;
}
