/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Isfault = boolean;
export type OrderSeries = number;

export interface Series {
  name: Name;
  isfault: Isfault;
  order_series: OrderSeries;
  [k: string]: unknown;
}
